### ISSUE TITLE
it does not  provide results in associations 

### ISSUE THREAD

**Issue by santoshkumar611** [mongoid/mongoid_search#105]
mongoid_search provides only search results. when we looping through these results causes hitting of database and  data in associations also hitting again database . even  relevant_search option is also not working in getting data from associations

**Comment by sivagollapalli** [comment]
@santoshkumar611 Could you provide code snippet or test case?

**Comment by rtrv** [comment]
@santoshkumar611 can the isuue be closed by last version or is it just outdated?
