### ISSUE TITLE
Config search to not ignore dots

### ISSUE THREAD

**Issue by sveredyuk** [mongoid/mongoid_search#106]
I have field with ip address like '10.0.10.0' and Mongoid::Search create one keyword only '10'. How to tune search to ignore dots ?

**Comment by dblock** [comment]
Probably a bug, feel free to PR.

**Comment by sveredyuk** [comment]
@dblock https://github.com/mongoid/mongoid_search/blob/master/lib/mongoid_search/util.rb#L44
Seems strip just ignored some symbols, what about to make this configurable ?

**Comment by Loschcode** [comment]
I've the same issue with dates like 2017-08-10 which are considered "2017", "08", "10" while it's supposed to be a complete date search.

@sveredyuk have you fixed this issue on your own ?

**Comment by sveredyuk** [comment]
@Loschcode Yeah, I have to monkey-patch this gem)

```ruby
# Mogoid::Search Overwrite
module Mongoid::Search::Util
  def self.normalize_keywords(text)
    ligatures     = Mongoid::Search.ligatures
    ignore_list   = Mongoid::Search.ignore_list
    stem_keywords = Mongoid::Search.stem_keywords
    stem_proc     = Mongoid::Search.stem_proc

    return [] if text.blank?
    text = text.to_s.
      mb_chars.
      normalize(:kd).
      downcase.
      to_s.
      gsub(/[_:;'\"`,?|+={}()!@#%^&*<>~\$\-\\\/\[\]]/, ' '). # strip symbols
      gsub(/[#{ligatures.keys.join("")}]/) {|c| ligatures[c]}.
      split(' ').
      reject { |word| word.size < Mongoid::Search.minimum_word_size }
    text = text.reject { |word| ignore_list.include?(word) } unless ignore_list.blank?
    text = text.map(&stem_proc) if stem_keywords
    text
  end
end

module Mongoid::Search
  def set_keywords
    self._keywords = Mongoid::Search::Util.keywords(self, self.search_fields)
      .flatten
      .reject{|k| k.nil? || k.empty?}
      .push(*self.search_fields)
      .flatten.map(&:to_s).uniq.sort
  end
end
```

**Comment by Loschcode** [comment]
@sveredyuk I actually didn't expect any answer so I went forward and made a fork earlier today ; to add a configuration option and slightly change the structure of what you kinda monkey patched on your end.

Thanks for your solution though ;)

https://github.com/Loschcode/mongoid_search

I'll make a pull request, might not suit everyone but it works in production for me.

**Comment by Loschcode** [comment]
Pull request https://github.com/mongoid/mongoid_search/pull/110

**Comment by sveredyuk** [comment]
my pr is waiting more than half a year - https://github.com/mongoid/mongoid_search/pull/108

**Comment by Loschcode** [comment]
I've the feeling we will both wait for a while then, ouch

**Comment by dblock** [comment]
We need more maintainers for this repo, @sveredyuk @Loschcode you guys volunteer?

@mauriciozaffari is the sole owner of this right now, ping?

**Comment by dblock** [comment]
I opened https://github.com/mongoid/mongoid_search/issues/111 to discuss ownership.
