### ISSUE TITLE
Rake Aborted

### ISSUE THREAD

**Issue by BilalReffas** [mongoid/mongoid_search#109]
I'm trying to run the command `rake mongoid_search:index` The problem is receive 

> Don't know how to build task 'mongoid_search:index' (see --tasks)

Thank you for your help :)

**Comment by calvinsug** [comment]
same heree

**Comment by showaltb** [comment]
The 0.3.2 release is missing the `mongoid_search.rake` file for some reason.

I was able to make this work by using the current branch from github in my `Gemfile`:

    gem 'mongoid_search', github: 'mongoid/mongoid_search'

If you want/need to stay with 0.3.2, you can just grab the rake task and save it under your project's `lib/tasks`:

    curl https://raw.githubusercontent.com/mongoid/mongoid_search/master/lib/mongoid_search/tasks/mongoid_search.rake >lib/tasks/mongoid_search.rake

**Comment by rtrv** [comment]
Rake task exists at 0.3.3 and 0.3.4
