### ISSUE TITLE
Optional punctuation regex

### ISSUE THREAD

**Issue by rtrv** [mongoid/mongoid_search#112]
#63 is closed, but I suppose there is a need to make this regex optional. I personally need to search for IPs, emails and abbreviations with dots. Could it be a part of the gem, If that PR is covered by tests?

**Comment by sveredyuk** [comment]
Maybe #108 helps you?

**Comment by rtrv** [comment]
@sveredyuk yes, it's the thing! Thanks. Do you need any help with that PR to get it merged? There are no tests yet, as I can see and Travis fails

**Comment by sveredyuk** [comment]
If you have a time to find why Travis fails, I will add Readme changes

**Comment by rtrv** [comment]
Look at closed PRs: https://github.com/mongoid/mongoid_search/pulls?page=1&q=is%3Apr+is%3Aclosed

Travis failed on every merged PR. So Travis is not the problem for #108, just test coverage and Readme. And reaction of anybody in charge to merge PRs, of course.

I'll try to fix Travis separately from your PR to work proper. I also have issues with dependencies (concretely ActiveSupport) and RSpec fails due to ActiveSupport `call`.

If you have about 10 minutes to discuss on it or provide me your experience in testing this gem, please, write me on Gitter

**Comment by sveredyuk** [comment]
Ok, just need to find 10-20 minutes to work on Readme

**Comment by rtrv** [comment]
Closed by #108
