### ISSUE TITLE
Update gem at RubyGems

### ISSUE THREAD

**Issue by rtrv** [mongoid/mongoid_search#120]
Currently there is just 0.3.2

I don't have rights to update it, which should be done with `gem owner mongoid_search --add artemkrivonozhko@gmail.com` by any owner.

Gem build also fails because it requires file with name "VERSION" which is missing

**Comment by rtrv** [comment]
When that's done, it'd be good to make proper tags and releases at github

**Comment by dblock** [comment]
I unassigned myself from here, happy to see this gem being maintained!

**Comment by rtrv** [comment]
0.3.3 and 0.3.4 are now at RubyGems! Lets fix current problems and get done test coverage for last added features to release 0.4
