### ISSUE TITLE
If special characters are not stripped, they may lead to Regex error

### ISSUE THREAD

**Issue by rtrv** [mongoid/mongoid_search#122]
After making strips and accents configurable, if I want my keywords contain for example parenthesis, `full_text_search('text(')` will raise an error. The string which is passed into `search_for` should be wrapped by `Regex.escape()`

**Comment by sivagollapalli** [comment]
@rtrv As per my understanding whenever we do search `text (` (ie., if search query has special characters) then it throws an error. Am I right?

**Comment by rtrv** [comment]
@sivagollapalli yes, you're right. I have to do `Regex.escape(text)` to pass `text` into `full_text_search` as an argument to avoid the problem now, so I think escaping should be done inside the gem
